<?php echo $form->textFieldRow($model,'totalbiayatindakan',array('readonly'=>true,'class'=>'span2 integer2', 'onkeyup'=>"return $(this).focusNextInputField(event);")); ?>
<?php echo $form->textFieldRow($model,'totalbiayaoa',array('readonly'=>true,'class'=>'span2 integer2', 'onkeyup'=>"return $(this).focusNextInputField(event);")); ?>
<?php echo $form->textFieldRow($model,'totaldiscount',array('readonly'=>true,'class'=>'span2 integer2', 'onkeyup'=>"return $(this).focusNextInputField(event);")); ?>
<?php echo $form->textFieldRow($model,'totalpembebasan',array('readonly'=>true,'class'=>'span2 integer2', 'onkeyup'=>"return $(this).focusNextInputField(event);")); ?>
<?php echo $form->textFieldRow($model,'totalsubsidiasuransi',array('readonly'=>true,'class'=>'span2 integer2', 'onkeyup'=>"return $(this).focusNextInputField(event);")); ?>
<?php echo $form->textFieldRow($model,'totalsubsidipemerintah',array('readonly'=>true,'class'=>'span2 integer2', 'onkeyup'=>"return $(this).focusNextInputField(event);")); ?>
<?php echo $form->textFieldRow($model,'totalsubsidirs',array('readonly'=>true,'class'=>'span2 integer2', 'onkeyup'=>"return $(this).focusNextInputField(event);")); ?>
<?php echo $form->textFieldRow($model,'totaliurbiaya',array('readonly'=>true,'class'=>'span2 integer2', 'onkeyup'=>"return $(this).focusNextInputField(event);")); ?>
<?php echo $form->textFieldRow($model,'totalbayartindakan',array('readonly'=>true,'class'=>'span2 integer2', 'onkeyup'=>"return $(this).focusNextInputField(event);")); ?>
