 <style>
    
    @media screen {
    #whiteBg {
        display: none;
    }
}

@media print {
   #footer {
     width:100%;  
     position: fixed;
     bottom: 0;
   }
     
   
   body {
     margin: 0;
}
}
</style>
<?php 

if($caraPrint=='EXCEL')
{
    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment;filename="'.$judulLaporan.'-'.date("Y/m/d").'.xls"');
    header('Cache-Control: max-age=0');     
}
echo $this->renderPartial('application.views.headerReport.headerLaporanTransaksi',array('judulLaporan'=>$judulLaporan, 'periode'=>'Periode : '.$periode, 'colspan'=>14));

if ($caraPrint != 'GRAFIK')
$this->renderPartial($this->path_view.'pendapatanRuangan/_tablePendapatanRuangan', array('model'=>$model, 'caraPrint'=>$caraPrint)); 

if ($caraPrint == 'GRAFIK')
echo $this->renderPartial($this->path_view.'_grafik', array('model'=>$model, 'data'=>$data, 'caraPrint'=>$caraPrint), true); 

?>
 <div id="footer" style = "width:100%;">
     <div style = "display:inline-block;float:left;text-align:left;">
         <i><b>Generated By Ehealthsyaaaaaaaaaaaaaaaas</b></i>
     </div>
     <div style = "text-align:right;float:right;">
         <i><b>Print Count :</b></i>
     </div>
 </div>