<?php

class LaporanWaktuTungguController extends MyAuthController
{
  public $layout = '//layouts/column1';
  public $defaultAction = 'index';
  public $path_view = 'farmasiApotek.views.laporanWaktuTunggu.';
  public $judul_laporan = 'Waktu Tunggu';
  public function actionIndex()
  {
    $this->pageTitle = Yii::app()->name . " - Lembar Resep";
    $model = new LaporanwaktutungguresepV('search');
    $format = new MyFormatter;
    $tgl_awal = date('Y-m-d');
    $tgl_akhir = date('Y-m-d');
    $tahun = date('Y');
    $model->unsetAttributes();
    $model->jns_periode = "hari";
    $model->tgl_awal = date('Y-m-d', strtotime('first day of this month'));
    $model->tgl_akhir = date('Y-m-d');
    $model->bln_awal = date('Y-m', strtotime('first day of january'));
    $model->bln_akhir = date('Y-m');
    $model->thn_awal = date('Y');
    $model->thn_akhir = date('Y');
    //==========================================
    if (isset($_GET['LaporanwaktutungguresepV'])) {


      $model->attributes = $_GET['LaporanwaktutungguresepV'];
      $model->jns_periode = $_GET['LaporanwaktutungguresepV']['jns_periode'];
      $model->tgl_awal = $format->formatDateTimeForDb($_GET['LaporanwaktutungguresepV']['tgl_awal']);
      $model->tgl_akhir = $format->formatDateTimeForDb($_GET['LaporanwaktutungguresepV']['tgl_akhir']);
      $model->bln_awal = $format->formatMonthForDb($_GET['LaporanwaktutungguresepV']['bln_awal']);
      $model->bln_akhir = $format->formatMonthForDb($_GET['LaporanwaktutungguresepV']['bln_akhir']);
      $model->thn_awal = $_GET['LaporanwaktutungguresepV']['thn_awal'];
      $model->thn_akhir = $_GET['LaporanwaktutungguresepV']['thn_akhir'];
      $bln_akhir = $model->bln_akhir . "-" . date("t", strtotime($model->bln_akhir));
      $thn_akhir = $model->thn_akhir . "-" . date("m-t", strtotime($model->thn_akhir . "-12"));
      switch ($model->jns_periode) {
        case 'bulan':
          $model->tgl_awal = $model->bln_awal . "-01";
          $model->tgl_akhir = $bln_akhir;
          break;
        case 'tahun':
          $model->tgl_awal = $model->thn_awal . "-01-01";
          $model->tgl_akhir = $thn_akhir;
          break;
        default:
          null;
      }
      $model->tgl_awal = $model->tgl_awal . " 00:00:00";
      $model->tgl_akhir = $model->tgl_akhir . " 23:59:59";
    }

    $this->render($this->path_view . '.index', array(
      'judul_laporan'  => $this->judul_laporan,
      'model' => $model,
      'tgl_awal' => $tgl_awal,
      'tgl_akhir' => $tgl_akhir,
      'tahun' => $tahun
    ));
  }

  /**
   * BUAT CETAK LAPORAN
   */
  public function actionPrintLaporan()
  {
    $model = new LaporanwaktutungguresepV('search');
    $judulLaporan = "Laporan ".$this->judul_laporan;

    //Data Grafik       
    $data['title'] = "Laporan ".$this->judul_laporan;
    $data['type'] = (isset($_REQUEST['type']) ? $_REQUEST['type'] : null);
    $data['nama_pegawai'] = LoginpemakaiK::model()->findByPk(Yii::app()->user->id)->pegawai->nama_pegawai;
    if (isset($_REQUEST['LaporanwaktutungguresepV'])) {
      $model->attributes = $_REQUEST['LaporanwaktutungguresepV'];
      $format = new MyFormatter();
      $model->tgl_awal = $format->formatDateTimeForDb($_REQUEST['LaporanwaktutungguresepV']['tgl_awal']);
      $model->tgl_akhir = $format->formatDateTimeForDb($_REQUEST['LaporanwaktutungguresepV']['tgl_akhir']);
    }
    
    $caraPrint = $_REQUEST['caraPrint'];
    if ($caraPrint == "PRINTRINCIAN") {
      $caraPrint = 'PRINT';
      $data['rincian'] = true;
    }
    $target = '_print';

    $this->printFunction($model, $data, $caraPrint, $judulLaporan, $target);
  }

  protected function printFunction($model, $data, $caraPrint, $judulLaporan, $target, $grafik = null)
  {
    $format = new MyFormatter();
    $periode = $format->formatDateTimeForUser($model->tgl_awal) . ' s/d ' . $format->formatDateTimeForUser($model->tgl_akhir);
    if ($caraPrint == 'PRINT' || $caraPrint == 'GRAFIK') {
      $this->layout = '//layouts/printWindows2';
      $this->render($target, array('model' => $model, 'periode' => $periode, 'data' => $data, 'judulLaporan' => $judulLaporan, 'caraPrint' => $caraPrint));
    } else if ($caraPrint == 'EXCEL') {
      $this->layout = '//layouts/printExcel';
      $this->render($target, array('model' => $model, 'periode' => $periode, 'data' => $data, 'judulLaporan' => $judulLaporan, 'caraPrint' => $caraPrint));
    } else if ($_REQUEST['caraPrint'] == 'PDF') {
      $ukuranKertasPDF = Yii::app()->user->getState('ukuran_kertas');                  //Ukuran Kertas Pdf
      $posisi = Yii::app()->user->getState('posisi_kertas');                           //Posisi L->Landscape,P->Portait
      $mpdf = new MyPDF60('', $ukuranKertasPDF);
      $footer = '<table width="100%"><tr>'
        . '<td style = "text-align:left;font-size:8px;"><i><b>Generated By Ehealthsys</b></i></td>'
        . '<td style = "text-align:right;font-size:8px;"><i><b>Print Count :</b></i></td>'
        . '</tr></table>';
      $mpdf->SetHtmlFooter($footer, 'E');
      $mpdf->SetHtmlFooter($footer, 'O');
      $stylesheet = file_get_contents(Yii::getPathOfAlias('webroot.css') . '/bootstrap.css');
      $mpdf->WriteHTML($stylesheet, 1);
      $mpdf->AddPage($posisi, '', '', '', '', 20, 20, 15, 30, 20, 20);
      $mpdf->WriteHTML($this->renderPartial($target, array('model' => $model, 'periode' => $periode, 'data' => $data, 'judulLaporan' => $judulLaporan, 'caraPrint' => $caraPrint), true));
      $mpdf->Output($judulLaporan . '_' . date('d-m-Y') . '.pdf', 'I');
    }
  }
  //===========================================================================
}
