<?php

class LaporanJumlahResepController extends MyAuthController
{
  public $layout = '//layouts/column1';
  public $defaultAction = 'index';
  public $path_view = 'farmasiApotek.views.laporanJumlahResep.';
  public $judul_laporan = 'Laporan Jumlah Resep';

  public function actionIndex()
  {
    $this->pageTitle = Yii::app()->name . " - Jumlah Resep";
    $model = new LaporanjumlahresepV('search');
    $format = new MyFormatter;
    $tgl_awal = $model->tgl_awal = date('Y-m-d');
    $tgl_akhir = $model->tgl_akhir = date('Y-m-d');
    $tahun = date('Y');
    /**
     * sesuai lookup_m.lookup_type = 'laporanjumlahresep' (urutkan sesuai lookup_m.urutan asc)
     */
    $lookup_m = LookupM::model()->getItems('laporanjumlahresep');
    //==========================================
    if (isset($_GET['LaporanjumlahresepV'])) {
      $model->attributes = $_GET['LaporanjumlahresepV'];
      $model->tgl_awal = $tgl_awal = $format->formatDateTimeForDb($_GET['LaporanjumlahresepV']['tgl_awal']);
      $model->tgl_akhir = $tgl_akhir =  $format->formatDateTimeForDb($_GET['LaporanjumlahresepV']['tgl_akhir']);
    }

    /**
     * get data
     */
    $criteria = new CDbCriteria;
    $criteria->addBetweenCondition('DATE(tglpenjualan)', $tgl_awal, $tgl_akhir);
    $resultLaporanJumlahResep = LaporanjumlahresepV::model()->findAll($criteria);
    //==========================================
    $this->render($this->path_view . '.index', array(
      'judul_laporan'  => $this->judul_laporan,
      'model' => $model,
      'lookup_m' => $lookup_m,
      'tgl_awal' => $tgl_awal,
      'tgl_akhir' => $tgl_akhir,
      'resultLaporanJumlahResep' => $resultLaporanJumlahResep,
      'tahun' => $tahun
    ));
  }

  /**
   * BUAT CETAK LAPORAN
   */
  public function actionPrintLaporan()
  {
    $model = new LaporanjumlahresepV('search');
    $judulLaporan = $this->judul_laporan;

    //Data Grafik       
    $data['title'] = $this->judul_laporan;
    $data['type'] = (isset($_REQUEST['type']) ? $_REQUEST['type'] : null);
    $data['nama_pegawai'] = LoginpemakaiK::model()->findByPk(Yii::app()->user->id)->pegawai->nama_pegawai;
    if (isset($_REQUEST['LaporanjumlahresepV'])) {
      $model->attributes = $_REQUEST['LaporanjumlahresepV'];
      $format = new MyFormatter();
      $model->tgl_awal = $tgl_awal = $format->formatDateTimeForDb($_REQUEST['LaporanjumlahresepV']['tgl_awal']);
      $model->tgl_akhir = $tgl_akhir = $format->formatDateTimeForDb($_REQUEST['LaporanjumlahresepV']['tgl_akhir']);
    }

    $caraPrint = $_REQUEST['caraPrint'];
    if ($caraPrint == "PRINTRINCIAN") {
      $caraPrint = 'PRINT';
      $data['rincian'] = true;
    }
    $target = '_print';
    
    $this->printFunction($model, $data, $caraPrint, $judulLaporan, $target, $tgl_awal, $tgl_akhir);
  }

  protected function printFunction($model, $data, $caraPrint, $judulLaporan, $target, $tgl_awal, $tgl_akhir, $grafik = null)
  {
    /**
     * get data
     */
    $criteria = new CDbCriteria;
    $criteria->addBetweenCondition('DATE(tglpenjualan)', $tgl_awal, $tgl_akhir);
    $resultLaporanJumlahResep = LaporanjumlahresepV::model()->findAll($criteria);

    /**
     * sesuai lookup_m.lookup_type = 'laporanjumlahresep' (urutkan sesuai lookup_m.urutan asc)
     */
    $lookup_m = LookupM::model()->getItems('laporanjumlahresep');

    $format = new MyFormatter();
    $periode = $format->formatDateTimeForUser($model->tgl_awal) . ' s/d ' . $format->formatDateTimeForUser($model->tgl_akhir);
    if ($caraPrint == 'PRINT' || $caraPrint == 'GRAFIK') {
      $this->layout = '//layouts/printWindows2';
      $this->render($target, array('model' => $model, 
      'periode' => $periode, 'data' => $data, 
      'judulLaporan' => $judulLaporan, 'caraPrint' => $caraPrint,
      'lookup_m' => $lookup_m, 'resultLaporanJumlahResep' => $resultLaporanJumlahResep,
      'tgl_awal' => $tgl_awal, 'tgl_akhir' => $tgl_akhir));
    } else if ($caraPrint == 'EXCEL') {
      $this->layout = '//layouts/printExcel';
      $this->render($target, array('model' => $model, 
      'periode' => $periode, 'data' => $data, 
      'judulLaporan' => $judulLaporan, 'caraPrint' => $caraPrint,
      'lookup_m' => $lookup_m, 'resultLaporanJumlahResep' => $resultLaporanJumlahResep,
      'tgl_awal' => $tgl_awal, 'tgl_akhir' => $tgl_akhir));
    } else if ($_REQUEST['caraPrint'] == 'PDF') {
      $ukuranKertasPDF = Yii::app()->user->getState('ukuran_kertas');                  //Ukuran Kertas Pdf
      $posisi = Yii::app()->user->getState('posisi_kertas');                           //Posisi L->Landscape,P->Portait
      $mpdf = new MyPDF60('', $ukuranKertasPDF);
      $footer = '<table width="100%"><tr>'
        . '<td style = "text-align:left;font-size:8px;"><i><b>Generated By Ehealthsys</b></i></td>'
        . '<td style = "text-align:right;font-size:8px;"><i><b>Print Count :</b></i></td>'
        . '</tr></table>';
      $mpdf->SetHtmlFooter($footer, 'E');
      $mpdf->SetHtmlFooter($footer, 'O');
      $stylesheet = file_get_contents(Yii::getPathOfAlias('webroot.css') . '/bootstrap.css');
      $mpdf->WriteHTML($stylesheet, 1);
      $mpdf->AddPage($posisi, '', '', '', '', 20, 20, 15, 30, 20, 20);
      $mpdf->WriteHTML($this->renderPartial($target, array('model' => $model, 
      'periode' => $periode, 'data' => $data, 
      'judulLaporan' => $judulLaporan, 'caraPrint' => $caraPrint,
      'lookup_m' => $lookup_m, 'resultLaporanJumlahResep' => $resultLaporanJumlahResep,
      'tgl_awal' => $tgl_awal, 'tgl_akhir' => $tgl_akhir), true));
      $mpdf->Output($judulLaporan . '_' . date('d-m-Y') . '.pdf', 'I');
    }
  }
  //===========================================================================
}
